//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootingClub.Exceptions {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesException() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShootingClub.Exceptions.ResourceMessagesException", typeof(ResourceMessagesException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A ação é inválida para o CPF informado..
        /// </summary>
        public static string ACAO_INVALIDA_CPF_INFORMADO {
            get {
                return ResourceManager.GetString("ACAO_INVALIDA_CPF_INFORMADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você já possui um clube registrado..
        /// </summary>
        public static string ADMIN_JA_POSSUI_CLUBE {
            get {
                return ResourceManager.GetString("ADMIN_JA_POSSUI_CLUBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Administrador não possui um clube para que possa realizar essa ação..
        /// </summary>
        public static string ADMIN_NAO_POSSUI_CLUBE_CADASTRADO {
            get {
                return ResourceManager.GetString("ADMIN_NAO_POSSUI_CLUBE_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhuma arma foi encontrada..
        /// </summary>
        public static string ARMA_NAO_ENCONTRADA {
            get {
                return ResourceManager.GetString("ARMA_NAO_ENCONTRADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O calibre está inválido..
        /// </summary>
        public static string CALIBRE_ARMA_INVALIDO {
            get {
                return ResourceManager.GetString("CALIBRE_ARMA_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Certificado de registro do clube está inválido..
        /// </summary>
        public static string CLUBE_CR_INVALIDO {
            get {
                return ResourceManager.GetString("CLUBE_CR_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CNPJ está inválido..
        /// </summary>
        public static string CNPJ_INVALIDO {
            get {
                return ResourceManager.GetString("CNPJ_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CNPJ já registrado..
        /// </summary>
        public static string CNPJ_JA_CADASTRADO {
            get {
                return ResourceManager.GetString("CNPJ_JA_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O CPF  está inválido..
        /// </summary>
        public static string CPF_INVALIDO {
            get {
                return ResourceManager.GetString("CPF_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF já registrado..
        /// </summary>
        public static string CPF_JA_CADASTRADO {
            get {
                return ResourceManager.GetString("CPF_JA_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível encontrar um usuário com esse CPF..
        /// </summary>
        public static string CPF_USUARIO_INEXISTENTE {
            get {
                return ResourceManager.GetString("CPF_USUARIO_INEXISTENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O formato da CR está inválido..
        /// </summary>
        public static string CR_INVALIDO {
            get {
                return ResourceManager.GetString("CR_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O CR já está cadastrado já foi cadastrado..
        /// </summary>
        public static string CR_JA_CADASTRADO {
            get {
                return ResourceManager.GetString("CR_JA_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dados inconsistentes para o tipo de posse da arma..
        /// </summary>
        public static string DADOS_INCONSISTENTES_TIPO_POSSE {
            get {
                return ResourceManager.GetString("DADOS_INCONSISTENTES_TIPO_POSSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data do certificado está inválida..
        /// </summary>
        public static string DATA_CERTIFICADO_INVALIDA {
            get {
                return ResourceManager.GetString("DATA_CERTIFICADO_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de expedição do CRAF está inválido..
        /// </summary>
        public static string DATA_EXPEDICAO_CRAF_INVALIDA {
            get {
                return ResourceManager.GetString("DATA_EXPEDICAO_CRAF_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data da filiação está inválida..
        /// </summary>
        public static string DATA_FILIACAO_INVALIDA {
            get {
                return ResourceManager.GetString("DATA_FILIACAO_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de nascimento está inválida..
        /// </summary>
        public static string DATA_NASCIMENTO_INVALIDA {
            get {
                return ResourceManager.GetString("DATA_NASCIMENTO_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de renovação da filiação está inválida.
        /// </summary>
        public static string DATA_RENOVACAO_FILIACAO_INVALIDA {
            get {
                return ResourceManager.GetString("DATA_RENOVACAO_FILIACAO_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de vencimento da CR está inválido..
        /// </summary>
        public static string DATA_VENCIMENTO_CR_INVALIDA {
            get {
                return ResourceManager.GetString("DATA_VENCIMENTO_CR_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de vencimento da CR deve ser informado..
        /// </summary>
        public static string DATA_VENCIMENTO_CR_REQUERIDA {
            get {
                return ResourceManager.GetString("DATA_VENCIMENTO_CR_REQUERIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O CR deve ser informado para possuir uma data de vencimento..
        /// </summary>
        public static string DATA_VENCIMENTO_CR_SEM_CR {
            get {
                return ResourceManager.GetString("DATA_VENCIMENTO_CR_SEM_CR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O email está inválido..
        /// </summary>
        public static string EMAIL_INVALIDO {
            get {
                return ResourceManager.GetString("EMAIL_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email já registrado..
        /// </summary>
        public static string EMAIL_JA_CADASTRADO {
            get {
                return ResourceManager.GetString("EMAIL_JA_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email e/ou senha inválidos..
        /// </summary>
        public static string EMAIL_OU_SENHA_INVALIDO {
            get {
                return ResourceManager.GetString("EMAIL_OU_SENHA_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O bairro informado é inválido..
        /// </summary>
        public static string ENDERECO_BAIRRO_INVALIDO {
            get {
                return ResourceManager.GetString("ENDERECO_BAIRRO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A cidade informado é inválido..
        /// </summary>
        public static string ENDERECO_CIDADE_INVALIDO {
            get {
                return ResourceManager.GetString("ENDERECO_CIDADE_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Endereço não pode conter caracteres especiais..
        /// </summary>
        public static string ENDERECO_COM_CARACTERES_ESPECIAIS {
            get {
                return ResourceManager.GetString("ENDERECO_COM_CARACTERES_ESPECIAIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O estado informado é inválido..
        /// </summary>
        public static string ENDERECO_ESTADO_INVALIDO {
            get {
                return ResourceManager.GetString("ENDERECO_ESTADO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O numero do endereço é inválido..
        /// </summary>
        public static string ENDERECO_NUMERO_INVALIDO {
            get {
                return ResourceManager.GetString("ENDERECO_NUMERO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O país informado é inválido..
        /// </summary>
        public static string ENDERECO_PAIS_INVALIDO {
            get {
                return ResourceManager.GetString("ENDERECO_PAIS_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A rua está inválida..
        /// </summary>
        public static string ENDERECO_RUA_INVALIDA {
            get {
                return ResourceManager.GetString("ENDERECO_RUA_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro Desconhecido..
        /// </summary>
        public static string ERRO_DESCONHECIDO {
            get {
                return ResourceManager.GetString("ERRO_DESCONHECIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O local de registro está vazio..
        /// </summary>
        public static string LOCAL_REGISTRO_VAZIO {
            get {
                return ResourceManager.GetString("LOCAL_REGISTRO_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A marca está vazio..
        /// </summary>
        public static string MARCA_ARMA_VAZIO {
            get {
                return ResourceManager.GetString("MARCA_ARMA_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome não pode ter caracteres especiais..
        /// </summary>
        public static string NOME_COM_CARACTERES_ESPECIAIS {
            get {
                return ResourceManager.GetString("NOME_COM_CARACTERES_ESPECIAIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome está inválido..
        /// </summary>
        public static string NOME_INVALIDO {
            get {
                return ResourceManager.GetString("NOME_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O número do certificado está vazio..
        /// </summary>
        public static string NUMERO_CERTIFICADO_VAZIO {
            get {
                return ResourceManager.GetString("NUMERO_CERTIFICADO_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O número da filiação está inválido..
        /// </summary>
        public static string NUMERO_FILIACAO_INVALIDO {
            get {
                return ResourceManager.GetString("NUMERO_FILIACAO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O número de Filiação já foi cadastrado..
        /// </summary>
        public static string NUMERO_FILIACAO_JA_CADASTRADO {
            get {
                return ResourceManager.GetString("NUMERO_FILIACAO_JA_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O numero da nota fiscal está vazio..
        /// </summary>
        public static string NUMERO_NF_VAZIO {
            get {
                return ResourceManager.GetString("NUMERO_NF_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O número de registro da PF está vazio..
        /// </summary>
        public static string NUMERO_REGISTRO_PF_VAZIO {
            get {
                return ResourceManager.GetString("NUMERO_REGISTRO_PF_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O número de série está vazio..
        /// </summary>
        public static string NUMERO_SERIE_ARMA_VAZIO {
            get {
                return ResourceManager.GetString("NUMERO_SERIE_ARMA_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O número de série já foi registrado..
        /// </summary>
        public static string NUMERO_SERIE_JA_REGISTRADO {
            get {
                return ResourceManager.GetString("NUMERO_SERIE_JA_REGISTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O número de SIGMA está inválido..
        /// </summary>
        public static string NUMERO_SIGMA_INVALIDO {
            get {
                return ResourceManager.GetString("NUMERO_SIGMA_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O número do SINARM está vazio..
        /// </summary>
        public static string NUMERO_SINARM_VAZIO {
            get {
                return ResourceManager.GetString("NUMERO_SINARM_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O token não foi enviado..
        /// </summary>
        public static string SEM_TOKEN {
            get {
                return ResourceManager.GetString("SEM_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha inserida é diferente da senha atual..
        /// </summary>
        public static string SENHA_DIFERENTE_ATUAL {
            get {
                return ResourceManager.GetString("SENHA_DIFERENTE_ATUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha está inválida, a senha deve conter 8 caracteres entre eles letra minúscula, uma maiúscula, um dígito e um símbolo especial.
        /// </summary>
        public static string SENHA_INVALIDA {
            get {
                return ResourceManager.GetString("SENHA_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha está vazia..
        /// </summary>
        public static string SENHA_VAZIA {
            get {
                return ResourceManager.GetString("SENHA_VAZIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O SFPC da vinculação está inválido..
        /// </summary>
        public static string SFPC_VINCULACAO_INVALIDA {
            get {
                return ResourceManager.GetString("SFPC_VINCULACAO_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O SFPC vinculado deve ser fornecido..
        /// </summary>
        public static string SFPC_VINCULACAO_REQUERIDO {
            get {
                return ResourceManager.GetString("SFPC_VINCULACAO_REQUERIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O CR deve ser informado para possuir um SFPC vinculado..
        /// </summary>
        public static string SFPC_VINCULACAO_SEM_CR {
            get {
                return ResourceManager.GetString("SFPC_VINCULACAO_SEM_CR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O tipo está vazio..
        /// </summary>
        public static string TIPO_ARMA_VAZIO {
            get {
                return ResourceManager.GetString("TIPO_ARMA_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O tipo da posse da arma é inválido..
        /// </summary>
        public static string TIPO_POSSE_ARMA_INVALIDO {
            get {
                return ResourceManager.GetString("TIPO_POSSE_ARMA_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O tipo de possse da arma não pode ser alterado..
        /// </summary>
        public static string TIPO_POSSE_NAO_PODE_SER_ALTERADO {
            get {
                return ResourceManager.GetString("TIPO_POSSE_NAO_PODE_SER_ALTERADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum usuário foi encontrado..
        /// </summary>
        public static string USUARIO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("USUARIO_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuário não tem permissão para acessar esse recurso..
        /// </summary>
        public static string USUARIO_SEM_PERMISSAO_PARA_ACESSAR_RECURSO {
            get {
                return ResourceManager.GetString("USUARIO_SEM_PERMISSAO_PARA_ACESSAR_RECURSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de validade do certificado está inválido..
        /// </summary>
        public static string VALIDADE_CERTIFICADO_INVALIDA {
            get {
                return ResourceManager.GetString("VALIDADE_CERTIFICADO_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de validade do CRAF está inválido..
        /// </summary>
        public static string VALIDADE_CRAF_INVALIDA {
            get {
                return ResourceManager.GetString("VALIDADE_CRAF_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de validade da GTE está inválida..
        /// </summary>
        public static string VALIDADE_GTE_INVALIDA {
            get {
                return ResourceManager.GetString("VALIDADE_GTE_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de validade está invalida..
        /// </summary>
        public static string VALIDADE_PF_INVALIDA {
            get {
                return ResourceManager.GetString("VALIDADE_PF_INVALIDA", resourceCulture);
            }
        }
    }
}
