//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootingClub.Exceptions {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesException() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShootingClub.Exceptions.ResourceMessagesException", typeof(ResourceMessagesException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O CPF  está inválido..
        /// </summary>
        public static string CPF_INVALIDO {
            get {
                return ResourceManager.GetString("CPF_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF já registrado..
        /// </summary>
        public static string CPF_JA_CADASTRADO {
            get {
                return ResourceManager.GetString("CPF_JA_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de nascimento está inválida..
        /// </summary>
        public static string DATA_NASCIMENTO_INVALIDA {
            get {
                return ResourceManager.GetString("DATA_NASCIMENTO_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de renovação da filiação está inválida.
        /// </summary>
        public static string DATA_RENOVACAO_FILIACAO_INVALIDA {
            get {
                return ResourceManager.GetString("DATA_RENOVACAO_FILIACAO_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O email está inválido..
        /// </summary>
        public static string EMAIL_INVALIDO {
            get {
                return ResourceManager.GetString("EMAIL_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email já registrado..
        /// </summary>
        public static string EMAIL_JA_CADASTRADO {
            get {
                return ResourceManager.GetString("EMAIL_JA_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email e/ou senha inválidos..
        /// </summary>
        public static string EMAIL_OU_SENHA_INVALIDO {
            get {
                return ResourceManager.GetString("EMAIL_OU_SENHA_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O bairro informado é inválido..
        /// </summary>
        public static string ENDERECO_BAIRRO_INVALIDO {
            get {
                return ResourceManager.GetString("ENDERECO_BAIRRO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A cidade informado é inválido..
        /// </summary>
        public static string ENDERECO_CIDADE_INVALIDO {
            get {
                return ResourceManager.GetString("ENDERECO_CIDADE_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O estado informado é inválido..
        /// </summary>
        public static string ENDERECO_ESTADO_INVALIDO {
            get {
                return ResourceManager.GetString("ENDERECO_ESTADO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O numerio do endereço é inválido..
        /// </summary>
        public static string ENDERECO_NUMERO_INVALIDO {
            get {
                return ResourceManager.GetString("ENDERECO_NUMERO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O país informado é inválido..
        /// </summary>
        public static string ENDERECO_PAIS_INVALIDO {
            get {
                return ResourceManager.GetString("ENDERECO_PAIS_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A rua está inválida..
        /// </summary>
        public static string ENDERECO_RUA_INVALIDA {
            get {
                return ResourceManager.GetString("ENDERECO_RUA_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro Desconhecido..
        /// </summary>
        public static string ERRO_DESCONHECIDO {
            get {
                return ResourceManager.GetString("ERRO_DESCONHECIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome está inválido..
        /// </summary>
        public static string NOME_INVALIDO {
            get {
                return ResourceManager.GetString("NOME_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O número da filiação está inválido..
        /// </summary>
        public static string NUMERO_FILIACAO_INVALIDO {
            get {
                return ResourceManager.GetString("NUMERO_FILIACAO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O número de Filiação já foi cadastrado..
        /// </summary>
        public static string NUMERO_FILIACAO_JA_CADASTRADO {
            get {
                return ResourceManager.GetString("NUMERO_FILIACAO_JA_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O token não foi enviado..
        /// </summary>
        public static string SEM_TOKEN {
            get {
                return ResourceManager.GetString("SEM_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha inserida é diferente da senha atual..
        /// </summary>
        public static string SENHA_DIFERENTE_ATUAL {
            get {
                return ResourceManager.GetString("SENHA_DIFERENTE_ATUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha está inválida, a senha deve conter 8 caracteres entre eles letra minúscula, uma maiúscula, um dígito e um símbolo especial.
        /// </summary>
        public static string SENHA_INVALIDA {
            get {
                return ResourceManager.GetString("SENHA_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha está vazia..
        /// </summary>
        public static string SENHA_VAZIA {
            get {
                return ResourceManager.GetString("SENHA_VAZIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuário não tem permissão para acessar esse recurso..
        /// </summary>
        public static string USUARIO_SEM_PERMISSAO_PARA_ACESSAR_RECURSO {
            get {
                return ResourceManager.GetString("USUARIO_SEM_PERMISSAO_PARA_ACESSAR_RECURSO", resourceCulture);
            }
        }
    }
}
